name: 🎏 Glitch Pinger 🏓🌊🔎
on:
  workflow_dispatch: # Whenever manually run from actions-tab
  schedule:
    - cron: "*/35 * * * *" #Every 35 Mins
#------------------------------------------------------------------------------------#  
jobs:
  Ping:
    runs-on: ubuntu-latest
    timeout-minutes: 05 # Can't afford to finish the 2000 Minutes quotes    
    permissions:
      contents: write
      
    steps:        
      - name: 🏓 Ping Streamers 🌊
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #Aseem0xff
          #Self
          curl -qfksSL "https://delirious-woolen-syrup.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://delirious-woolen-syrup.glitch.me" -o "/dev/null" --max-time 5
          #Check-Host.net
          curl -qfksSL "https://check-host.net/check-http?host=delirious-woolen-syrup.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          #da.gd
          curl -qfksSL "https://da.gd/up/delirious-woolen-syrup.glitch.me" --max-time 5          
          #AvalynSouvlaki
          #Self
          curl -qfksSL "https://coordinated-assorted-rumba.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://coordinated-assorted-rumba.glitch.me" -o "/dev/null" --max-time 5
          #Check-Host.net
          curl -qfksSL "https://check-host.net/check-http?host=coordinated-assorted-rumba.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          #Da.gd
          curl -qfksSL "https://da.gd/up/coordinated-assorted-rumba.glitch.me" --max-time 5
          #LiamOFlaberry
          #Self
          curl -qfksSL "https://lizard-petalite-espadrille.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://lizard-petalite-espadrille.glitch.me" -o "/dev/null" --max-time 5
          #Check-Host.net
          curl -qfksSL "https://check-host.net/check-http?host=lizard-petalite-espadrille.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          #Da.gd
          curl -qfksSL "https://da.gd/up/lizard-petalite-espadrille.glitch.me" --max-time 5
        continue-on-error: true
        
      - name: 🏓 Ping Inscopers 🔎
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #AjamX101
          #Self
          curl -qfksSL "https://snow-flint-rosemary.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://snow-flint-rosemary.glitch.me" -o "/dev/null" --max-time 5
          #Check-Host.net
          curl -qfksSL "https://check-host.net/check-http?host=snow-flint-rosemary.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          #da.gd
          curl -qfksSL "https://da.gd/up/snow-flint-rosemary.glitch.me" --max-time 5
          #Orion0xff
          #Self
          curl -qfksSL "https://hilarious-elastic-wrist.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://hilarious-elastic-wrist.glitch.me" -o "/dev/null" --max-time 5
          #Check-Host.net
          curl -qfksSL "https://check-host.net/check-http?host=hilarious-elastic-wrist.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          #da.gd
          curl -qfksSL "https://da.gd/up/hilarious-elastic-wrist.glitch.me" --max-time 5
          #Polaris0xff
          curl -qfksSL "https://boulder-material-rattlesnake.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://boulder-material-rattlesnake.glitch.me" -o "/dev/null" --max-time 5
          #Check-Host.net
          curl -qfksSL "https://check-host.net/check-http?host=boulder-material-rattlesnake.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          #da.gd
          curl -qfksSL "https://da.gd/up/boulder-material-rattlesnake.glitch.me" --max-time 5
          ##Externals
          #https://glitch.com/@athakursc12
          curl -qfksSL "https://imminent-rainy-tip.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://imminent-rainy-tip.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://check-host.net/check-http?host=imminent-rainy-tip.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          curl -qfksSL "https://da.gd/up/imminent-rainy-tip.glitch.me" --max-time 5
          #https://glitch.com/@bhusal0x1
          curl -qfksSL "https://skitter-cloudy-licorice.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://skitter-cloudy-licorice.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://check-host.net/check-http?host=skitter-cloudy-licorice.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          curl -qfksSL "https://da.gd/up/skitter-cloudy-licorice.glitch.me" --max-time 5
          #https://glitch.com/@santaarie83
          curl -qfksSL "https://wandering-clammy-marmoset.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://wandering-clammy-marmoset.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://check-host.net/check-http?host=wandering-clammy-marmoset.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          curl -qfksSL "https://da.gd/up/wandering-clammy-marmoset.glitch.me" --max-time 5
          #https://glitch.com/@nikeshsapkota977
          curl -qfksSL "https://jeweled-glaze-fold.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://jeweled-glaze-fold.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://check-host.net/check-http?host=jeweled-glaze-fold.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          curl -qfksSL "https://da.gd/up/jeweled-glaze-fold.glitch.me" --max-time 5
          #https://glitch.com/@sapkota98nikesh
          curl -qfksSL "https://neat-pyrite-koi.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://neat-pyrite-koi.glitch.me" -o "/dev/null" --max-time 5
          curl -qfksSL "https://check-host.net/check-http?host=neat-pyrite-koi.glitch.me" -H "Accept: application/json" -o "/dev/null" --max-time 5
          curl -qfksSL "https://da.gd/up/neat-pyrite-koi.glitch.me" --max-time 5
        continue-on-error: true
